name: CI/CD Pipeline

# Trigger on push to the main branch and pull requests
on:
  push:
    branches:
      - development
  workflow_dispatch:    
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build the project using Maven
      - name: Build with Maven
        run: mvn -B clean install

      # Step 5: Run tests using Maven
      - name: Run tests
        run: mvn test

  deploy:
    # Deployment job that depends on the success of the build job
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Checkout the code again
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Deploy (placeholder step - replace with actual deployment)
      # Example: Deploy to a server, cloud service, or other environment
      - name: Deploy Application
        run: echo "Deploying application..." # Replace with your deployment script or tool command
