name: My First Workflow

run-name: ${{ github.actor }} is learning GitHub Actions


on: 
 push:
 workflow_dispatch:

jobs:
  echo-print:
   runs-on: ubuntu-latest
   

        

   steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4.5.0
      with:
       java-version: '17'
       distribution: 'temurin'
    - run: mvn --batch-mode --update-snapshots verify
    - run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v4
      with:
       name: Package
       path: staging
 
